// ============================================
// Export Engine â€” Client-Side Document Generation
// Generates PPTX, DOCX, PDF from mind map data
// ============================================

import { jsPDF } from 'jspdf';
import type { MindMapNode } from '@/types';

// ---- Utility ----
function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function getChildren(nodes: MindMapNode[], parentId: string): MindMapNode[] {
  return nodes.filter(n => n.parentId === parentId);
}

// ============================================
// PPTX Export (using PptxGenJS loaded from CDN)
// ============================================
export async function exportToPPTX(nodes: MindMapNode[], title: string): Promise<void> {
  // Dynamically load PptxGenJS
  const PptxGenJS = await loadScript<any>(
    'https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/dist/pptxgen.bundle.js',
    'PptxGenJS'
  );

  const pptx = new PptxGenJS();
  pptx.author = 'MedMind AI';
  pptx.title = title;
  pptx.subject = 'Medical Mind Map';
  pptx.layout = 'LAYOUT_WIDE';

  // Color palette
  const colors = {
    bg: '0a0e17',
    bgLight: '1a2236',
    surface: '253349',
    text: 'e8edf5',
    textMuted: '94a3b8',
    brand: '06d6a0',
    purple: '7c3aed',
    pink: 'f72585',
    amber: 'fbbf24',
    blue: '00b4d8',
  };

  const accents = [colors.brand, colors.purple, colors.pink, colors.amber, colors.blue];
  const roots = nodes.filter(n => !n.parentId);

  // ---- Title Slide ----
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: colors.bg };
  
  // Decorative accent bar
  titleSlide.addShape(pptx.shapes.RECTANGLE, {
    x: 0, y: 0, w: 0.08, h: '100%', fill: { color: colors.brand },
  });

  titleSlide.addText(title, {
    x: 1, y: 1.5, w: 10, h: 1.5,
    fontSize: 44, fontFace: 'Georgia', color: colors.text, bold: true,
  });

  titleSlide.addText(`${nodes.length} topics Â· Generated by MedMind AI`, {
    x: 1, y: 3.2, w: 10, h: 0.5,
    fontSize: 14, fontFace: 'Arial', color: colors.textMuted,
  });

  titleSlide.addText(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), {
    x: 1, y: 3.8, w: 10, h: 0.4,
    fontSize: 11, fontFace: 'Arial', color: '64748b',
  });

  // ---- Overview Slide ----
  if (roots.length > 0) {
    const overviewSlide = pptx.addSlide();
    overviewSlide.background = { color: colors.bg };
    overviewSlide.addShape(pptx.shapes.RECTANGLE, { x: 0, y: 0, w: '100%', h: 0.04, fill: { color: colors.brand } });

    overviewSlide.addText('Overview', {
      x: 0.8, y: 0.4, w: 10, h: 0.7,
      fontSize: 28, fontFace: 'Georgia', color: colors.text, bold: true,
    });

    roots.forEach((root, i) => {
      const accent = accents[i % accents.length];
      const y = 1.5 + i * 0.65;
      
      overviewSlide.addShape(pptx.shapes.RECTANGLE, {
        x: 0.8, y: y + 0.08, w: 0.25, h: 0.25, fill: { color: accent },
        rectRadius: 0.04,
      });

      overviewSlide.addText(root.data.title, {
        x: 1.3, y, w: 9, h: 0.45,
        fontSize: 16, fontFace: 'Arial', color: colors.text,
      });
    });
  }

  // ---- Content Slides ----
  roots.forEach((root, rootIdx) => {
    const children = getChildren(nodes, root.id);
    const accent = accents[rootIdx % accents.length];

    // Root topic slide with children as bullets
    const rootSlide = pptx.addSlide();
    rootSlide.background = { color: colors.bg };
    rootSlide.addShape(pptx.shapes.RECTANGLE, { x: 0, y: 0, w: '100%', h: 0.04, fill: { color: accent } });

    rootSlide.addText(root.data.title, {
      x: 0.8, y: 0.4, w: 10, h: 0.8,
      fontSize: 28, fontFace: 'Georgia', color: colors.text, bold: true,
    });

    if (root.data.content) {
      rootSlide.addText(root.data.content, {
        x: 0.8, y: 1.2, w: 10, h: 0.6,
        fontSize: 13, fontFace: 'Arial', color: colors.textMuted, italic: true,
      });
    }

    // List children
    children.forEach((child, ci) => {
      const y = (root.data.content ? 2.0 : 1.5) + ci * 0.55;
      
      rootSlide.addText('â–¸', {
        x: 0.8, y, w: 0.3, h: 0.4,
        fontSize: 14, fontFace: 'Arial', color: accent,
      });

      rootSlide.addText(child.data.title, {
        x: 1.2, y, w: 9.5, h: 0.4,
        fontSize: 15, fontFace: 'Arial', color: colors.text,
      });
    });

    // Detail slides for each child
    children.forEach((child, ci) => {
      const grandchildren = getChildren(nodes, child.id);
      if (grandchildren.length === 0 && !child.data.content) return;

      const childSlide = pptx.addSlide();
      childSlide.background = { color: colors.bg };
      childSlide.addShape(pptx.shapes.RECTANGLE, { x: 0, y: 0, w: '100%', h: 0.04, fill: { color: accent } });

      // Breadcrumb
      childSlide.addText(`${root.data.title}  â€º`, {
        x: 0.8, y: 0.3, w: 5, h: 0.3,
        fontSize: 10, fontFace: 'Arial', color: '64748b',
      });

      childSlide.addText(child.data.title, {
        x: 0.8, y: 0.6, w: 10, h: 0.7,
        fontSize: 24, fontFace: 'Georgia', color: colors.text, bold: true,
      });

      if (child.data.content) {
        childSlide.addText(child.data.content, {
          x: 0.8, y: 1.4, w: 10, h: 0.8,
          fontSize: 13, fontFace: 'Arial', color: colors.textMuted,
          lineSpacingMultiple: 1.4,
        });
      }

      // Grandchildren
      const startY = child.data.content ? 2.4 : 1.6;
      grandchildren.forEach((gc, gi) => {
        const y = startY + gi * 0.7;
        
        childSlide.addText(`â–¸  ${gc.data.title}`, {
          x: 0.8, y, w: 10, h: 0.3,
          fontSize: 14, fontFace: 'Arial', color: colors.text, bold: true,
        });

        if (gc.data.content) {
          childSlide.addText(gc.data.content.substring(0, 150), {
            x: 1.2, y: y + 0.3, w: 9.5, h: 0.3,
            fontSize: 11, fontFace: 'Arial', color: colors.textMuted,
          });
        }
      });
    });
  });

  // Save
  const filename = `${title.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '_')}.pptx`;
  await pptx.writeFile({ fileName: filename });
}

// ============================================
// DOCX Export (using docx.js loaded from CDN)
// ============================================
export async function exportToDOCX(nodes: MindMapNode[], title: string): Promise<void> {
  const docx = await loadScript<any>(
    'https://cdn.jsdelivr.net/npm/docx@8.5.0/build/index.umd.js',
    'docx'
  );

  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, 
          BorderStyle, PageBreak, TableOfContents, Header, Footer, PageNumber } = docx;

  const roots = nodes.filter(n => !n.parentId);
  const sections: any[] = [];

  // Title page
  sections.push(
    new Paragraph({
      spacing: { before: 4000 },
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({ text: title, bold: true, size: 56, font: 'Georgia', color: '06d6a0' }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 400 },
      children: [
        new TextRun({ text: `${nodes.length} topics Â· Generated by MedMind AI`, size: 22, color: '94a3b8', font: 'Arial' }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 200 },
      children: [
        new TextRun({
          text: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
          size: 20, color: '64748b', font: 'Arial',
        }),
      ],
    }),
    new Paragraph({ children: [new PageBreak()] }),
  );

  // Table of contents header
  sections.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: 'Table of Contents', bold: true, size: 32, font: 'Georgia' })],
    }),
    new Paragraph({ spacing: { after: 200 }, children: [] }),
  );

  // TOC entries
  roots.forEach(root => {
    sections.push(
      new Paragraph({
        spacing: { before: 100 },
        children: [new TextRun({ text: `â–   ${root.data.title}`, size: 22, font: 'Arial' })],
      })
    );
    getChildren(nodes, root.id).forEach(child => {
      sections.push(
        new Paragraph({
          indent: { left: 720 },
          children: [new TextRun({ text: `â–¸  ${child.data.title}`, size: 20, color: '64748b', font: 'Arial' })],
        })
      );
    });
  });

  sections.push(new Paragraph({ children: [new PageBreak()] }));

  // Content
  roots.forEach((root, idx) => {
    const accentColors = ['06d6a0', '7c3aed', 'f72585', 'fbbf24', '00b4d8'];
    const accent = accentColors[idx % accentColors.length];

    // H1
    sections.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
        border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: accent } },
        children: [new TextRun({ text: root.data.title, bold: true, size: 32, font: 'Georgia', color: accent })],
      })
    );

    if (root.data.content) {
      sections.push(
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({ text: root.data.content, size: 22, font: 'Arial', color: '475569' })],
        })
      );
    }

    // Children
    buildDocxSections(nodes, root.id, 2, sections, docx, accent);
  });

  const doc = new Document({
    creator: 'MedMind AI',
    title: title,
    description: `Medical mind map: ${title}`,
    styles: {
      default: {
        document: {
          run: { font: 'Arial', size: 22, color: '1e293b' },
          paragraph: { spacing: { line: 340 } },
        },
      },
    },
    sections: [{
      properties: {
        page: {
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      headers: {
        default: new Header({
          children: [new Paragraph({
            alignment: AlignmentType.RIGHT,
            children: [new TextRun({ text: `${title}  Â·  MedMind AI`, size: 16, color: '94a3b8', font: 'Arial' })],
          })],
        }),
      },
      footers: {
        default: new Footer({
          children: [new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({ text: 'Page ', size: 16, color: '94a3b8' }),
              new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '94a3b8' }),
              new TextRun({ text: ' of ', size: 16, color: '94a3b8' }),
              new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: '94a3b8' }),
            ],
          })],
        }),
      },
      children: sections,
    }],
  });

  const blob = await Packer.toBlob(doc);
  const filename = `${title.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '_')}.docx`;
  downloadBlob(blob, filename);
}

function buildDocxSections(nodes: MindMapNode[], parentId: string, level: number, sections: any[], docx: any, accent: string) {
  const { Paragraph, TextRun, HeadingLevel, BorderStyle } = docx;
  const children = getChildren(nodes, parentId);

  const headingLevels = [
    HeadingLevel.HEADING_1, HeadingLevel.HEADING_2, HeadingLevel.HEADING_3,
    HeadingLevel.HEADING_4, HeadingLevel.HEADING_5, HeadingLevel.HEADING_6,
  ];

  children.forEach(child => {
    // Heading
    sections.push(
      new Paragraph({
        heading: headingLevels[Math.min(level - 1, 5)],
        spacing: { before: 300, after: 100 },
        children: [
          new TextRun({
            text: child.data.title,
            bold: true,
            size: Math.max(20, 30 - level * 3),
            font: level <= 2 ? 'Georgia' : 'Arial',
            color: level <= 2 ? accent : '334155',
          }),
          child.data.aiGenerated ? new TextRun({ text: '  âœ¨', size: 16 }) : new TextRun(''),
        ],
      })
    );

    // Content
    if (child.data.content) {
      sections.push(
        new Paragraph({
          spacing: { after: 200 },
          children: [new TextRun({
            text: child.data.content,
            size: 21,
            font: 'Arial',
            color: '475569',
          })],
        })
      );
    }

    // Tags
    if (child.data.tags?.length > 0) {
      sections.push(
        new Paragraph({
          spacing: { after: 100 },
          children: [new TextRun({
            text: `Tags: ${child.data.tags.join(', ')}`,
            size: 16,
            font: 'Arial',
            color: '94a3b8',
            italics: true,
          })],
        })
      );
    }

    // Recurse
    buildDocxSections(nodes, child.id, level + 1, sections, docx, accent);
  });
}

// ============================================
// PDF Export (using jsPDF)
// ============================================
export async function exportToPDF(nodes: MindMapNode[], title: string): Promise<void> {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const roots = nodes.filter(n => !n.parentId);
  const pageW = 210, pageH = 297;
  const margin = 25;
  const contentW = pageW - margin * 2;
  let y = margin;

  const colors = {
    brand: [6, 214, 160] as [number, number, number],
    purple: [124, 58, 237] as [number, number, number],
    pink: [247, 37, 133] as [number, number, number],
    amber: [251, 191, 36] as [number, number, number],
    blue: [0, 180, 216] as [number, number, number],
    text: [30, 41, 59] as [number, number, number],
    textMuted: [100, 116, 139] as [number, number, number],
    light: [148, 163, 184] as [number, number, number],
  };
  const accentArr = [colors.brand, colors.purple, colors.pink, colors.amber, colors.blue];

  function checkPageBreak(needed: number) {
    if (y + needed > pageH - margin) {
      pdf.addPage();
      y = margin;
      // Header
      pdf.setFontSize(8);
      pdf.setTextColor(...colors.light);
      pdf.text(`${title}  Â·  MedMind AI`, pageW - margin, 15, { align: 'right' });
      y = 25;
    }
  }

  function addLine(color: [number, number, number]) {
    pdf.setDrawColor(...color);
    pdf.setLineWidth(0.5);
    pdf.line(margin, y, margin + contentW, y);
    y += 5;
  }

  // ---- Title Page ----
  // Accent bar
  pdf.setFillColor(...colors.brand);
  pdf.rect(0, 0, 3, pageH, 'F');

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(36);
  pdf.setTextColor(...colors.text);
  pdf.text(title, margin + 5, 80);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(12);
  pdf.setTextColor(colors.textMuted[0], colors.textMuted[1], colors.textMuted[2]);
  pdf.text(`${nodes.length} topics Â· Generated by MedMind AI`, margin + 5, 95);

  pdf.setFontSize(10);
  pdf.setTextColor(...colors.light);
  pdf.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), margin + 5, 105);

  // ---- TOC ----
  pdf.addPage();
  y = margin;

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(22);
  pdf.setTextColor(...colors.text);
  pdf.text('Table of Contents', margin, y);
  y += 15;

  roots.forEach((root, i) => {
    checkPageBreak(20);
    const accent = accentArr[i % accentArr.length];
    
    pdf.setFillColor(...accent);
    pdf.rect(margin, y - 3, 3, 3, 'F');
    
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.setTextColor(...colors.text);
    pdf.text(root.data.title, margin + 8, y);
    y += 7;

    getChildren(nodes, root.id).forEach(child => {
      checkPageBreak(7);
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(10);
      pdf.setTextColor(colors.textMuted[0], colors.textMuted[1], colors.textMuted[2]);
      pdf.text(`â–¸  ${child.data.title}`, margin + 15, y);
      y += 5;
    });
    y += 3;
  });

  // ---- Content ----
  roots.forEach((root, rootIdx) => {
    pdf.addPage();
    y = margin;
    const accent = accentArr[rootIdx % accentArr.length];

    // Accent bar top
    pdf.setFillColor(...accent);
    pdf.rect(0, 0, pageW, 2, 'F');

    // H1
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(24);
    pdf.setTextColor(...accent);
    pdf.text(root.data.title, margin, y + 8);
    y += 15;

    addLine(accent);

    if (root.data.content) {
      checkPageBreak(15);
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(10);
      pdf.setTextColor(colors.textMuted[0], colors.textMuted[1], colors.textMuted[2]);
      const lines = pdf.splitTextToSize(root.data.content, contentW);
      pdf.text(lines, margin, y);
      y += lines.length * 5 + 5;
    }

    // Build content recursively
    renderPDFChildren(pdf, nodes, root.id, 2, margin, contentW, pageH, colors, accent,
      () => y, (newY: number) => { y = newY; },
      () => checkPageBreak(15)
    );
  });

  // Footer on each page
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(...colors.light);
    pdf.text(`Page ${i} of ${totalPages}`, pageW / 2, pageH - 10, { align: 'center' });
  }

  const filename = `${title.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '_')}.pdf`;
  pdf.save(filename);
}

function renderPDFChildren(
  pdf: jsPDF, nodes: MindMapNode[], parentId: string, level: number,
  margin: number, contentW: number, pageH: number,
  colors: any, accent: [number, number, number],
  getY: () => number, setY: (y: number) => void,
  checkBreak: () => void
) {
  const children = getChildren(nodes, parentId);
  const indent = Math.min((level - 1) * 8, 24);
  const fontSizes = [24, 16, 13, 11, 10];
  const fontSize = fontSizes[Math.min(level - 1, 4)];

  children.forEach(child => {
    let y = getY();
    checkBreak();
    y = getY();

    // Heading
    pdf.setFont('helvetica', level <= 2 ? 'bold' : 'normal');
    pdf.setFontSize(fontSize);
    const headingColor = level <= 2 ? accent : (colors.text as [number, number, number]);
    pdf.setTextColor(headingColor[0], headingColor[1], headingColor[2]);
    
    const titlePrefix = level > 2 ? 'â–¸ ' : '';
    pdf.text(`${titlePrefix}${child.data.title}`, margin + indent, y);
    y += fontSize * 0.5 + 3;

    // Content
    if (child.data.content) {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      pdf.setTextColor(colors.textMuted[0], colors.textMuted[1], colors.textMuted[2]);
      const lines = pdf.splitTextToSize(child.data.content, contentW - indent);
      pdf.text(lines, margin + indent + (level > 2 ? 5 : 0), y);
      y += lines.length * 4 + 3;
    }

    y += 2;
    setY(y);

    renderPDFChildren(pdf, nodes, child.id, level + 1, margin, contentW, pageH, colors, accent, getY, setY, checkBreak);
  });
}

// ============================================
// Script Loader
// ============================================
function loadScript<T>(url: string, globalName: string): Promise<T> {
  return new Promise((resolve, reject) => {
    // Check if already loaded
    if ((window as any)[globalName]) {
      resolve((window as any)[globalName]);
      return;
    }

    const script = document.createElement('script');
    script.src = url;
    script.onload = () => {
      if ((window as any)[globalName]) {
        resolve((window as any)[globalName]);
      } else {
        // Some UMD libs attach differently
        setTimeout(() => {
          resolve((window as any)[globalName]);
        }, 100);
      }
    };
    script.onerror = () => reject(new Error(`Failed to load ${url}`));
    document.head.appendChild(script);
  });
}

// ============================================
// Master Export Function
// ============================================
export async function exportMindMap(
  format: 'pptx' | 'docx' | 'pdf' | 'png' | 'json' | 'markdown',
  nodes: MindMapNode[],
  title: string,
  canvasElement?: HTMLElement
): Promise<void> {
  switch (format) {
    case 'pptx':
      await exportToPPTX(nodes, title);
      break;
    case 'docx':
      await exportToDOCX(nodes, title);
      break;
    case 'pdf':
      await exportToPDF(nodes, title);
      break;
    case 'png':
      if (canvasElement) {
        const { default: html2canvas } = await import('html-to-image' as any).catch(() => {
          // Fallback: use dom-to-image pattern
          return { default: null };
        });
        // Simple canvas screenshot approach
        const dataUrl = await toPng(canvasElement);
        const link = document.createElement('a');
        link.download = `${title.replace(/[^a-zA-Z0-9]/g, '_')}.png`;
        link.href = dataUrl;
        link.click();
      }
      break;
    case 'json':
      const jsonBlob = new Blob([JSON.stringify({ title, nodes, version: 2, exportedAt: new Date().toISOString() }, null, 2)], { type: 'application/json' });
      downloadBlob(jsonBlob, `${title.replace(/[^a-zA-Z0-9]/g, '_')}.json`);
      break;
    case 'markdown':
      const md = generateMarkdown(nodes, title);
      downloadBlob(new Blob([md], { type: 'text/markdown' }), `${title.replace(/[^a-zA-Z0-9]/g, '_')}.md`);
      break;
  }
}

async function toPng(element: HTMLElement): Promise<string> {
  const { toPng: toImage } = await import('html-to-image');
  return toImage(element, { quality: 0.95, backgroundColor: '#0a0e17', pixelRatio: 2 });
}

function generateMarkdown(nodes: MindMapNode[], title: string): string {
  let md = `# ${title}\n\n`;
  md += `> Generated by MedMind AI Â· ${new Date().toLocaleDateString()}\n\n---\n\n`;

  const roots = nodes.filter(n => !n.parentId);
  roots.forEach(root => {
    md += `## ${root.data.title}\n\n`;
    if (root.data.content) md += `${root.data.content}\n\n`;
    md += buildMdChildren(nodes, root.id, 3);
  });

  return md;
}

function buildMdChildren(nodes: MindMapNode[], parentId: string, level: number): string {
  const children = getChildren(nodes, parentId);
  let md = '';
  children.forEach(child => {
    const hashes = '#'.repeat(Math.min(level, 6));
    const aiTag = child.data.aiGenerated ? ' âœ¨' : '';
    md += `${hashes} ${child.data.title}${aiTag}\n\n`;
    if (child.data.content) md += `${child.data.content}\n\n`;
    if (child.data.tags?.length) md += `*Tags: ${child.data.tags.join(', ')}*\n\n`;
    md += buildMdChildren(nodes, child.id, level + 1);
  });
  return md;
}
